### ISSUE TITLE
百度云可以用，就是每月都要更新token

### ISSUE THREAD

**Issue by crylcy** [pizzamx/zimuku_for_kodi#25]
虽然知道有点厚脸皮，但是还是来反馈一下，大咖，能用一个不用每个月都更新token的服务不。。。。我用的是电视盒子，每个月一次更新真的是按断遥控器。。。。不论结果如何都多谢大咖   ：）

**Comment by pizzamx** [comment]
不知道啊，你可以找一找，找到了我适配一下

**Comment by crylcy** [comment]
好的好的，太感谢啦，我去找找其他

pizzamx ***@***.***> 于2024年6月30日周日 23:49写道：

**Comment by crylcy** [comment]
大咖，我找到一个免费的ocr接口，https://ocr.space/OCRAPI，用其中2.0引擎可能可以，水平有限，自己也不懂测试。您看一下是否能用？
![image](https://github.com/pizzamx/zimuku_for_kodi/assets/107782084/2f906e02-9dff-43db-9bc6-43fdf8b066b3)
![image](https://github.com/pizzamx/zimuku_for_kodi/assets/107782084/ee65d46b-accd-4624-a35e-56eaa66de7e8)

**Comment by pizzamx** [comment]
> 大咖，我找到一个免费的ocr接口，[https://ocr.space/OCRAPI，用其中2.0引擎可能可以，水平有限，自己也不懂测试。您看一下是否能用？](https://ocr.space/OCRAPI%EF%BC%8C%E7%94%A8%E5%85%B6%E4%B8%AD2.0%E5%BC%95%E6%93%8E%E5%8F%AF%E8%83%BD%E5%8F%AF%E4%BB%A5%EF%BC%8C%E6%B0%B4%E5%B9%B3%E6%9C%89%E9%99%90%EF%BC%8C%E8%87%AA%E5%B7%B1%E4%B9%9F%E4%B8%8D%E6%87%82%E6%B5%8B%E8%AF%95%E3%80%82%E6%82%A8%E7%9C%8B%E4%B8%80%E4%B8%8B%E6%98%AF%E5%90%A6%E8%83%BD%E7%94%A8%EF%BC%9F) ![image](https://private-user-images.githubusercontent.com/107782084/345770447-2f906e02-9dff-43db-9bc6-43fdf8b066b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTEwOTUsIm5iZiI6MTcyMDE5MDc5NSwicGF0aCI6Ii8xMDc3ODIwODQvMzQ1NzcwNDQ3LTJmOTA2ZTAyLTlkZmYtNDNkYi05YmM2LTQzZmRmOGIwNjZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNDQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODgwNzQ1OGFhYmI5NTIxMWUyZDY2MDgwM2U4NDg0NTQ2YjdiMDZhYTQwMTY4Y2M5ZTE2ZGVhMTI0MDlmNWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zu2BKJyxJJQ2esjRaGhaEEAi7mMnI3T7zshhJGd59X8) ![image](https://private-user-images.githubusercontent.com/107782084/345770663-ee65d46b-accd-4624-a35e-56eaa66de7e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTEwOTUsIm5iZiI6MTcyMDE5MDc5NSwicGF0aCI6Ii8xMDc3ODIwODQvMzQ1NzcwNjYzLWVlNjVkNDZiLWFjY2QtNDYyNC1hMzVlLTU2ZWFhNjZkZTdlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNDQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjkwNjE5ZDkxMGY1YzU1NzcwOWUzODk2YjEwOWVhZGNlMTA1M2E0ODFkZDViZGVkN2FiODRjM2Y2OWJmMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r4wscTsTMKSSZdJMry2AZMz4jKcSV51PvnyWd_OLxcU)

试了下，感觉质量不行， 35447 被识别成了"3544 71"（虽然继续试了两个成功了）

**Comment by crylcy** [comment]
好的，不好意思浪费您时间了。我明天看看腾讯云😅好像这个不用token

pizzamx ***@***.***> 于 2024年7月5日周五 22:49写道：

**Comment by crylcy** [comment]
> > 大咖，我找到一个免费的ocr接口，[https://ocr.space/OCRAPI，用其中2.0引擎可能可以，水平有限，自己也不懂测试。您看一下是否能用？](https://ocr.space/OCRAPI%EF%BC%8C%E7%94%A8%E5%85%B6%E4%B8%AD2.0%E5%BC%95%E6%93%8E%E5%8F%AF%E8%83%BD%E5%8F%AF%E4%BB%A5%EF%BC%8C%E6%B0%B4%E5%B9%B3%E6%9C%89%E9%99%90%EF%BC%8C%E8%87%AA%E5%B7%B1%E4%B9%9F%E4%B8%8D%E6%87%82%E6%B5%8B%E8%AF%95%E3%80%82%E6%82%A8%E7%9C%8B%E4%B8%80%E4%B8%8B%E6%98%AF%E5%90%A6%E8%83%BD%E7%94%A8%EF%BC%9F) ![image](https://private-user-images.githubusercontent.com/107782084/345770447-2f906e02-9dff-43db-9bc6-43fdf8b066b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTEwOTUsIm5iZiI6MTcyMDE5MDc5NSwicGF0aCI6Ii8xMDc3ODIwODQvMzQ1NzcwNDQ3LTJmOTA2ZTAyLTlkZmYtNDNkYi05YmM2LTQzZmRmOGIwNjZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNDQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODgwNzQ1OGFhYmI5NTIxMWUyZDY2MDgwM2U4NDg0NTQ2YjdiMDZhYTQwMTY4Y2M5ZTE2ZGVhMTI0MDlmNWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zu2BKJyxJJQ2esjRaGhaEEAi7mMnI3T7zshhJGd59X8) ![image](https://private-user-images.githubusercontent.com/107782084/345770663-ee65d46b-accd-4624-a35e-56eaa66de7e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTEwOTUsIm5iZiI6MTcyMDE5MDc5NSwicGF0aCI6Ii8xMDc3ODIwODQvMzQ1NzcwNjYzLWVlNjVkNDZiLWFjY2QtNDYyNC1hMzVlLTU2ZWFhNjZkZTdlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNDQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjkwNjE5ZDkxMGY1YzU1NzcwOWUzODk2YjEwOWVhZGNlMTA1M2E0ODFkZDViZGVkN2FiODRjM2Y2OWJmMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r4wscTsTMKSSZdJMry2AZMz4jKcSV51PvnyWd_OLxcU)
> 
> 试了下，感觉质量不行， 35447 被识别成了"3544 71"（虽然继续试了两个成功了）

大佬，我让同事试了一下腾讯云的，能识别，也是每月免费1000，是直接用key的不用token，不知道大佬是否有时间试一下？谢谢~~~
![image](https://github.com/user-attachments/assets/c3a8648c-e8e7-40e8-8fec-7dc9c66f2e9a)

**Comment by pizzamx** [comment]
可以用，但是测试案例时好时坏，有点搞不懂了

> > > 大咖，我找到一个免费的ocr接口，[https://ocr.space/OCRAPI，用其中2.0引擎可能可以，水平有限，自己也不懂测试。您看一下是否能用？
> > 
> > 
> > 试了下，感觉质量不行， 35447 被识别成了"3544 71"（虽然继续试了两个成功了）
> 
> 大佬，我让同事试了一下腾讯云的，能识别，也是每月免费1000，是直接用key的不用token，不知道大佬是否有时间试一下？谢谢~~~

**Comment by crylcy** [comment]
😂😅辛苦大咖了，那我还是老老实实每月换key.多谢多谢！👍

pizzamx ***@***.***> 于 2024年7月25日周四 22:56写道：

**Comment by pizzamx** [comment]
太诡异了，还是放出 0.2.0c 众测一下吧……我在全新的 21 环境是可以用的，但在升上来的 21 里面又报错。
使用注意：如果填了 TENCENT OCR SECRET ID，就用腾讯，否则用百度

**Comment by marvolo666** [comment]
> 放出 0.2.0c1 众测一下腾讯 OCR 吧，请在设置里配置好先

测试了一下 效果不大行  基本上过不了验证

**Comment by pizzamx** [comment]
> > 放出 0.2.0c1 众测一下腾讯 OCR 吧，请在设置里配置好先
> 
> 测试了一下 效果不大行 基本上过不了验证

是吗？我现在挺稳定的…这几天完全都不失败了

**Comment by marvolo666** [comment]
> > > 放出 0.2.0c1 众测一下腾讯 OCR 吧，请在设置里配置好先
> > 
> > 
> > 测试了一下 效果不大行 基本上过不了验证
> 
> 是吗？我现在挺稳定的…这几天完全都不失败了

我这边的症状就是，不管什么电影 搜索字幕都是找不到字幕

确认了一下SecretId和Key没有填错，引擎也选了腾讯云
还有什么设置需要专门注意一下的嘛 ？ 或者说哪里可以看到这个插件的日志输出？

**Comment by marvolo666** [comment]
2024-12-15 23:11:54.705 T:11180   debug <general>: ZiMuKuX::run - HANDLE PARAMS：{'action': 'search', 'languages': 'Chinese%20(Simple)', 'preferredlanguage': 'English'}
2024-12-15 23:11:54.706 T:11180   debug <CSettingsManager>: requested setting (ocr_url) was not found.
2024-12-15 23:11:54.706 T:11180   debug <CSettingsManager>: requested setting (bidu_ocr_at) was not found.
2024-12-15 23:11:54.707 T:11180    info <general>: ZiMuKuX::Search - Search for [盟军敢死队_(2024)_h265_AC3.mkv], item: {'temp': False, 'rar': False, 'mansearch': False, 'year': '2024', 'season': '', 'episode': '', 'tvshow': '', 'title': 'The Ministry of Ungentlemanly Warfare', 'file_original_path': 'smb://192.168.2.5/k3smb/movie/盟军敢死队 (2024)/盟军敢死队_(2024)_h265_AC3.mkv', '3let_language': ['zh-cn']}
2024-12-15 23:11:54.707 T:11180   debug <general>: ZiMuKuX::search - Search API url: https://so.zimuku.pw/search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare
2024-12-15 23:11:54.707 T:11180   error <general>: ZiMuKuX::get_page - requests GET [https://so.zimuku.pw/search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare]
2024-12-15 23:11:54.998 T:13864   debug <general>: CInputManager::ProcessMouse: trying mouse action leftclick
2024-12-15 23:12:00.573 T:11180    info <general>: Skipped 1 duplicate messages..
2024-12-15 23:12:00.573 T:11180   error <general>: ZiMuKuX::get_page - ERROR READING https://so.zimuku.pw/search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare: HTTPSConnectionPool(host='so.zimuku.pw', port=443): Max retries exceeded with url: /search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'so.zimuku.pw'. (_ssl.c:1136)")))
2024-12-15 23:12:00.573 T:11180   error <general>: ZiMuKuX::search - ERROR SEARCHING, E=(<class 'Exception'>: object of type 'NoneType' has no len())
2024-12-15 23:12:00.573 T:11180    info <general>: ZiMuKuX::Search - 字幕未找到，参数：{'temp': False, 'rar': False, 'mansearch': False, 'year': '2024', 'season': '', 'episode': '', 'tvshow': '', 'title': 'The Ministry of Ungentlemanly Warfare', 'file_original_path': 'smb://192.168.2.5/k3smb/movie/盟军敢死队 (2024)/盟军敢死队_(2024)_h265_AC3.mkv', '3let_language': ['zh-cn']}



开了一下debug日志看了一下

**Comment by marvolo666** [comment]
> 2024-12-15 23:11:54.705 T:11180 debug : ZiMuKuX::run - HANDLE PARAMS：{'action': 'search', 'languages': 'Chinese%20(Simple)', 'preferredlanguage': 'English'} 2024-12-15 23:11:54.706 T:11180 debug : requested setting (ocr_url) was not found. 2024-12-15 23:11:54.706 T:11180 debug : requested setting (bidu_ocr_at) was not found. 2024-12-15 23:11:54.707 T:11180 info : ZiMuKuX::Search - Search for [盟军敢死队_(2024)_h265_AC3.mkv], item: {'temp': False, 'rar': False, 'mansearch': False, 'year': '2024', 'season': '', 'episode': '', 'tvshow': '', 'title': 'The Ministry of Ungentlemanly Warfare', 'file_original_path': 'smb://192.168.2.5/k3smb/movie/盟军敢死队 (2024)/盟军敢死队_(2024)_h265_AC3.mkv', '3let_language': ['zh-cn']} 2024-12-15 23:11:54.707 T:11180 debug : ZiMuKuX::search - Search API url: https://so.zimuku.pw/search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare 2024-12-15 23:11:54.707 T:11180 error : ZiMuKuX::get_page - requests GET [https://so.zimuku.pw/search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare] 2024-12-15 23:11:54.998 T:13864 debug : CInputManager::ProcessMouse: trying mouse action leftclick 2024-12-15 23:12:00.573 T:11180 info : Skipped 1 duplicate messages.. 2024-12-15 23:12:00.573 T:11180 error : ZiMuKuX::get_page - ERROR READING https://so.zimuku.pw/search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare: HTTPSConnectionPool(host='so.zimuku.pw', port=443): Max retries exceeded with url: /search?q=The%20Ministry%20of%20Ungentlemanly%20Warfare (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'so.zimuku.pw'. (_ssl.c:1136)"))) 2024-12-15 23:12:00.573 T:11180 error : ZiMuKuX::search - ERROR SEARCHING, E=(<class 'Exception'>: object of type 'NoneType' has no len()) 2024-12-15 23:12:00.573 T:11180 info : ZiMuKuX::Search - 字幕未找到，参数：{'temp': False, 'rar': False, 'mansearch': False, 'year': '2024', 'season': '', 'episode': '', 'tvshow': '', 'title': 'The Ministry of Ungentlemanly Warfare', 'file_original_path': 'smb://192.168.2.5/k3smb/movie/盟军敢死队 (2024)/盟军敢死队_(2024)_h265_AC3.mkv', '3let_language': ['zh-cn']}
> 
> 开了一下debug日志看了一下

tmd  证书不匹配是什么鬼

**Comment by pizzamx** [comment]
你网址配置的是什么？我是 http://zimuku.org，不用 s

**Comment by marvolo666** [comment]
> 你网址配置的是什么？我是 [http://zimuku.org，不用](http://zimuku.org%EF%BC%8C%E4%B8%8D%E7%94%A8) s

https://so.zimuku.org 估计是https协议的原因 我去改一下试试

**Comment by marvolo666** [comment]
> > 你网址配置的是什么？我是 [http://zimuku.org，不用](http://zimuku.org%EF%BC%8C%E4%B8%8D%E7%94%A8) s
> 
> https://so.zimuku.org 估计是https协议的原因 我去改一下试试

经测试 http://zimuku.org 可行
